### ISSUE TITLE
支持 springboot3 的 graalvm 吗？

### ISSUE THREAD

**Issue by XDwanj** [mybatis-flex/mybatis-flex#134]

**Comment by w1036460519** [comment]
这个功能我也在关注，蹲守。

**Comment by PoisonGZ** [comment]
蹲一手

**Comment by SilenceJW** [comment]
跟着蹲一手

**Comment by PoisonGZ** [comment]
> 先搜搜 `MyBatis` 支不支持吧。

说不定大佬有解决方案呢，只能蹲蹲看喽

**Comment by adolphor** [comment]
> 先搜搜 `MyBatis` 支不支持吧。

MyBatis 已经支持了，Mybatis-Plus也支持了，希望可以尽快支持编译成native镜像，尝试了一下，报如下错误：
```
2024-08-28 22:33:02.954 flutter-flex-backend MateBook-Pro-2019.local [http-nio-8080-exec-1]  ERROR g.m.f.f.b.c.c.GlobalExceptionHandler -52- Exception: 
java.lang.RuntimeException: java.lang.NoSuchMethodException: com.user.service.UserService$$Lambda/0xe6184b238d60a0bf2fa9ea278d89e61d4deafe340.writeReplace()
        at com.mybatisflex.core.util.LambdaUtil.getSerializedLambda(LambdaUtil.java:94)
        at com.mybatisflex.core.util.LambdaUtil.lambda$getQueryColumn$2(LambdaUtil.java:79)
        at java.base@22.0.2/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1710)
        at com.mybatisflex.core.util.MapUtil.computeIfAbsent(MapUtil.java:64)
        at com.mybatisflex.core.util.LambdaUtil.getQueryColumn(LambdaUtil.java:77)
        at com.mybatisflex.core.query.QueryMethods.column(QueryMethods.java:2450)
        at com.mybatisflex.core.query.QueryWrapper.eq(QueryWrapper.java:834)
```
