### ISSUE TITLE
更新至 v1.5.9 后，IService#query() 和 BaseMapper#selectAll() 报错

### ISSUE THREAD

**Issue by CHExN** [mybatis-flex/mybatis-flex#146]
`IService#query()` 和 `BaseMapper#selectAll()` 调用的 `selectListByQuery(new QueryWrapper())` 报错：

_Caused by: java.lang.NullPointerException: Cannot invoke "com.mybatisflex.core.query.QueryColumn.toSelectSql(java.util.List, com.mybatisflex.core.dialect.IDialect)" because "queryColumn" is null
	at com.mybatisflex.core.query.CPI.toSelectSql(CPI.java:237)
	at com.mybatisflex.core.dialect.impl.CommonsDialectImpl.buildSelectColumnSql(CommonsDialectImpl.java:462)
	at com.mybatisflex.core.dialect.impl.CommonsDialectImpl.buildSelectSql(CommonsDialectImpl.java:383)
	at com.mybatisflex.core.dialect.impl.CommonsDialectImpl.forSelectByQuery(CommonsDialectImpl.java:331)
	at com.mybatisflex.core.provider.EntitySqlProvider.selectListByQuery(EntitySqlProvider.java:379)
	... 56 common frames omitted_

必须在 `QueryWrapper` 的 `#select()` 中加入 columns 才能生效

**Comment by CHExN** [comment]
已查找到[相同的问题](https://gitee.com/mybatis-flex/mybatis-flex/issues/I7VTLX)，下版本修复。
