### ISSUE TITLE
集成druid各种报错

### ISSUE THREAD

**Issue by leideqin** [mybatis-flex/mybatis-flex#169]
不知道什么问题，反正用最新的springboot 3.1，如果不依赖HikariCP，想使用druid的话，配置起来各种报错。不知道官方有没有适配druid。
-----------------------------------druid配置---------------------------------
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vipdb
    username: vip
    password: secret
    # druid 连接池管理
    druid:
      # 初始化连接池大小
      initial-size: 5
      # 连接池最大连接数
      max-active: 20
      # 每个连接上PSCache的最大值
      # 如果大于0，pool-prepared-statements自动开启
      max-pool-prepared-statement-per-connection-size: -1
      # 连接时最大等待时间（单位：毫秒）
      max-wait: 60000
      # 保持空闲连接不被关闭的最小生存时间（单位：毫秒）
      min-evictable-idle-time-millis: 300000
      # 连接池最小空闲数
      min-idle: 5

-----------------------------------报错信息-----------------------------------
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception with message: Cannot load driver class: org.h2.Driver
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.11.jar:6.0.11]
        ... 63 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot load driver class: org.h2.Driver
        at org.springframework.util.Assert.state(Assert.java:97) ~[spring-core-6.0.11.jar:6.0.11]
        at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:175) ~[spring-boot-autoconfigure-3.0.10.jar:3.0.10]
        at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.initializeDataSourceBuilder(DataSourceProperties.java:125) ~[spring-boot-autoconfigure-3.0.10.jar:3.0.10]
        at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Generic.dataSource(DataSourceConfiguration.java:150) ~[spring-boot-autoconfigure-3.0.10.jar:3.0.10]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.11.jar:6.0.11]
        ... 64 common frames omitted

**Comment by leideqin** [comment]
冤枉flex框架了，原来是druid的锅。遇到的同学去跟踪这个吧https://github.com/alibaba/druid/issues/5397

**Comment by yangfuhai** [comment]
另一个可能得原因也可以参考 https://mybatis-flex.com/zh/faq.html#spring-%E4%B8%8B%E4%BD%BF%E7%94%A8-druid-%E6%95%B0%E6%8D%AE%E6%BA%90%E6%97%A0%E6%B3%95%E5%90%AF%E5%8A%A8
