### ISSUE TITLE
两个不同的Mapper调用selectListByQueryAs(mapper, ResultDTO.class)会产生冲突IllegalArgumentException: Result Maps collection already contains key

### ISSUE THREAD

**Issue by piscesvivian** [mybatis-flex/mybatis-flex#268]
### 复现步骤（概要）
为了减少DTO数量，复用了部分动态统计的DTO

```java
class ResultDTO{
    private String id;
    private String count;
}
```

等效SQL：
```
query1 = select id, count(1) from table_a group by id;
query2 = select id, count(2) from table 
```
两个Mapper在**两个线程同时**执行查询
```java
mapper1.selectListByQueryAs(query1, ResultDTO.class)
mapper2.selectListByQueryAs(query2, ResultDTO.class)
```

调用栈：
调用出现异常（**出现首次异常之后，第二次调用不会再出现此问题**）
```java
java.lang.IllegalArgumentException: Result Maps collection already contains key package.ResultDTO
	at org.apache.ibatis.session.Configuration$StrictMap.put(Configuration.java:1071)
	at org.apache.ibatis.session.Configuration$StrictMap.put(Configuration.java:1024)
	at org.apache.ibatis.session.Configuration.addResultMap(Configuration.java:780)
	at com.mybatisflex.core.table.TableInfo.doBuildResultMap(TableInfo.java:1079)
	at com.mybatisflex.core.table.TableInfo.buildResultMap(TableInfo.java:992)
	at com.mybatisflex.core.mybatis.FlexConfiguration.replaceResultMap(FlexConfiguration.java:212)
	at com.mybatisflex.core.mybatis.FlexConfiguration.lambda$getMappedStatement$0(FlexConfiguration.java:146)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.apache.ibatis.util.MapUtil.computeIfAbsent(MapUtil.java:36)
	at com.mybatisflex.core.mybatis.FlexConfiguration.getMappedStatement(FlexConfiguration.java:145)
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.resolveMappedStatement(MapperMethod.java:254)
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:225)
	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:53)
	at org.apache.ibatis.binding.MapperProxy.lambda$cachedInvoker$0(MapperProxy.java:96)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.apache.ibatis.util.MapUtil.computeIfAbsent(MapUtil.java:36)
	at org.apache.ibatis.binding.MapperProxy.cachedInvoker(MapperProxy.java:94)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at jdk.proxy2/jdk.proxy2.$Proxy172.selectListByQuery(Unknown Source)
	at com.mybatisflex.core.BaseMapper.selectListByQueryAs(BaseMapper.java:640)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at org.apache.ibatis.binding.MapperProxy$DefaultMethodInvoker.invoke(MapperProxy.java:154)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at jdk.proxy2/jdk.proxy2.$Proxy172.selectListByQueryAs(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.mybatisflex.core.mybatis.MapperInvocationHandler.invoke(MapperInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy172.selectListByQueryAs(Unknown Source)
        --- 业务代码栈
```

这里面是否采用了mapper生成技术，导致两个DTO命名冲突了？

### 期望
自动区分两个Mapper，并且不产生冲突。

**Comment by Mhj520** [comment]
同问。特别是一些统计页面，所有接口都复用这个DTO
