### ISSUE TITLE
报错NoSuchMethodError

### ISSUE THREAD

**Issue by annata** [mybatis-flex/mybatis-flex#289]
测试了一下各个版本 1.7.5的时候还是好的,只要版本升级到1.7.7或者以后就会报错
Caused by: java.lang.NoSuchMethodError: 'java.util.Set org.apache.ibatis.executor.resultset.ResultSetWrapper.getMappedColumnNames(org.apache.ibatis.mapping.ResultMap, java.lang.String)'
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.applyPropertyMappings(FlexDefaultResultSetHandler.java:482)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.getRowValue(FlexDefaultResultSetHandler.java:417)

**Comment by yangfuhai** [comment]
mybatis 的版本太低，建议升级一下 mybatis 的版本
