### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.util.Set org.apache.ibatis.executor.resultset.ResultSetWrapper.getMappedColumnNames(org.apache.ibatis.mapping.ResultMap, java.lang.String)' 1.8.1 没有问题， 1.8.2 有问题

### ISSUE THREAD

**Issue by mgl-pub** [mybatis-flex/mybatis-flex#292]
jdk21
问题版本：mybatis-flex 1.8.2 (insert update 没有问题  baseMapper.selectAll , selectOne等查询有问题)
无问题版本：mybatis-flex 1.8.1

excpetion:

java.lang.NoSuchMethodError: 'java.util.Set org.apache.ibatis.executor.resultset.ResultSetWrapper.getMappedColumnNames(org.apache.ibatis.mapping.ResultMap, java.lang.String)'

	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.applyPropertyMappings(FlexDefaultResultSetHandler.java:481)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.getRowValue(FlexDefaultResultSetHandler.java:416)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.handleRowValuesForSimpleResultMap(FlexDefaultResultSetHandler.java:364)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.handleRowValues(FlexDefaultResultSetHandler.java:334)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.handleResultSet(FlexDefaultResultSetHandler.java:305)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.handleResultSets(FlexDefaultResultSetHandler.java:190)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:66)
	at com.mybatisflex.core.mybatis.FlexStatementHandler.query(FlexStatementHandler.java:101)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:65)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:336)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:158)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:110)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:90)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:142)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	at jdk.proxy2/jdk.proxy2.$Proxy75.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at jdk.proxy2/jdk.proxy2.$Proxy80.selectListByQuery(Unknown Source)
	at com.mybatisflex.core.BaseMapper.selectAll(BaseMapper.java:742)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at org.apache.ibatis.binding.MapperProxy$DefaultMethodInvoker.invoke(MapperProxy.java:154)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at jdk.proxy2/jdk.proxy2.$Proxy80.selectAll(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.mybatisflex.core.mybatis.MapperInvocationHandler.invoke(MapperInvocationHandler.java:103)
	at jdk.proxy2/jdk.proxy2.$Proxy80.selectAll(Unknown Source)
	at pub.mgl.mybatisflexdemo.MybatisFlexDemoApplicationTests.contextLoads(MybatisFlexDemoApplicationTests.kt:25)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

**Comment by mgl-pub** [comment]
已解决，手动升级mybatis版本到3.5.15

**Comment by GabbyMrH** [comment]
遇到了跟你的问题一样，我升级到最新版都没用。

**Comment by Nebulap** [comment]
```
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.mybatis</groupId>
                    <artifactId>mybatis</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
            <version>3.5.15</version>
        </dependency>
```
        解决
