### ISSUE TITLE
在使用kotlin的entity时，UpdateChain执行时，要求entity必须是非final

### ISSUE THREAD

**Issue by jackmiking** [mybatis-flex/mybatis-flex#361]
当entity为kotlin代码时，codeGen生成的entity不是open的，使用updateChain时，会报错，说某个entity是final的
```
java.lang.RuntimeException: com.xxx.Xxx is final
at org.apache.ibatis.javassist.util.proxy.ProxyFactory.checkClassAndSuperName(ProxyFactory.java:964)
	at org.apache.ibatis.javassist.util.proxy.ProxyFactory.makeSortedMethodList(ProxyFactory.java:988)
	at org.apache.ibatis.javassist.util.proxy.ProxyFactory.computeSignature(ProxyFactory.java:998)
	at org.apache.ibatis.javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:479)
```
需要对kotlin生成增加open的逻辑或者updateChain能兼容非open的？

**Comment by yangfuhai** [comment]
UpdateChain 时，mybatis-flex 要生成新的代理类，当你的 entity 为 final 时，就无法生成代理类了。这个只能修改你的 entity，没有第二个解决方案了。

**Comment by jackmiking** [comment]
自动回复：你的邮件我已经收到，如果需要回复的我会尽快回复的。感谢你的谅解····
