### ISSUE TITLE
建议：使用RelationOneToMany的valueField时不要求必须有中间表实体和Mapper

### ISSUE THREAD

**Issue by liujinxing** [mybatis-flex/mybatis-flex#393]
mybatis-flex 的关联查询功能太棒了，在项目中使用得非常爽，我们团队对此赞不绝口。[官方文档](https://mybatis-flex.com/zh/base/relations-query.html) 也非常棒，🫡

通过一个例子表达一下场景：

表之间的关联关系如下：

```mermaid
erDiagram
  "用户表" ||--o{ "用户与角色的绑定关系表": "包含"
  "角色表" ||--o{ "用户与角色的绑定关系表": "包含"
  
  "用户表" {
    int id "编号"
    string name "用户名称"
  }

  "用户与角色的绑定关系表" {
    int id "编号"
    int user_id "关联的用户编号"
    int role_id "关联的角色编号"
  }

  "角色表" {
    int id "编号"
    string name "角色名称"
  }
```

用户表对应的实体类 `User.java` ：

```java
@Data
@Table("用户表")
class User {
  @Id
  private Integer id;
  private String name;
  @RelationOneToMany(
        selfField = "id",
        targetTable = "用户与角色的绑定关系表",
        targetField = "userId",
        valueField = "roleId"
    )
  private List<Integer> roleIds;
}
```

用户表对应的 Mapper `UserMapper.java`：

```java
@Mapper
interface UserMapper extends BaseMapper<Integer> {}
```

用户与角色的绑定关系表对应的实体类 `UserRole.java`：

```java
@Data
@Table("用户与角色的绑定关系表")
public class UserRole {
  @Id
  private Integer userId;
  @Id
  private Integer roleId;
}
```

用户与角色的绑定关系表对应的Mapper `UserRoleMapper.java`：

```java
@Mapper
interface UserRoleMapper extends BaseMapper<UserRole> {}
```

上面的示例中 `User#roleIds` 属性值是通过 `valueField` 定义从 `用户与角色的绑定关系表` 中查询出来的 `role_id` 字段值。

上面的示例代码是可以工作的，前提是必须要定义`用户与角色的绑定关系表`的实体类和Mapper。但实际上这个关联表非常简单，只有与关联关系相关的两个字段，除了关联查询这个场景中需要这个实体，其他地方都不需要。（备注：我们扩展了 @RelationOneToMany 的用法，在保存主表时自动更新了关联表数据，所以其他地方并不需要此关联表的实体和Mapper）。我的建议是**能不能不定义关联表的实体和Mapper（即上例中的 `UserRole` 和 `UserRoleMapper`），就能实现上面的关联查询效果**。就像下面这个多对多场景：

用户表对应的实体类 `User.java` ：

```java
@Data
@Table("用户表")
class User {
  @Id
  private Integer id;
  private String name;
  @RelationManyToMany(
        joinTable = "角色表",
        joinSelfColumn = "user_id",
        joinTargetColumn = "role_id"
   )
  private List<Role> roles;
}
```

用户表对应的 Mapper `UserMapper.java`：

```java
@Mapper
interface UserMapper extends BaseMapper<Integer> {}
```

角色表对应的实体类 `Role.java`：

```java
@Data
@Table("角色表")
public class Role {
  @Id
  private Integer id;
  private Integer name;
}
```

角色表对应的Mapper `RoleMapper.java`：

```java
@Mapper
interface RoleMapper extends BaseMapper<Integer> {}
```

这个多对多关联查询就不要求定义 `UserRole.java` 和 `UserRoleMapper.java`。

**Comment by yangfuhai** [comment]
目前就是不要求定义 UserRole.java 和 UserRoleMapper.java 的。

**Comment by liujinxing** [comment]
在 `RelationManyToMany` 场景中确实不需要定义 `UserRole.java` 和 `UserRoleMapper.java`，但是在 `RelationOneToMany` 场景中不定义 `UserRole.java` 和 `UserRoleMapper.java`，运行上面的示例，则会抛出以下异常（mybatis-flex 1.9.6）：

```bash
java.lang.IllegalStateException: Can not find field by name "userId" from class: java.lang.Integer

	at com.mybatisflex.core.relation.AbstractRelation.<init>(AbstractRelation.java:99)
	at com.mybatisflex.core.relation.ToManyRelation.<init>(ToManyRelation.java:44)
	at com.mybatisflex.core.relation.OneToMany.<init>(OneToMany.java:26)
	at com.mybatisflex.core.relation.RelationManager.doGetRelations(RelationManager.java:262)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.mybatisflex.core.util.MapUtil.computeIfAbsent(MapUtil.java:64)
	at com.mybatisflex.core.relation.RelationManager.getRelations(RelationManager.java:243)
	at com.mybatisflex.core.relation.RelationManager.doQueryRelations(RelationManager.java:307)
	at com.mybatisflex.core.relation.RelationManager.queryRelations(RelationManager.java:276)
	at com.mybatisflex.core.util.MapperUtil.queryRelations(MapperUtil.java:257)
	at com.mybatisflex.core.BaseMapper.selectAllWithRelations(BaseMapper.java:854)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.mybatisflex.core.mybatis.binding.MybatisMapperProxy$DefaultMethodInvoker.invoke(MybatisMapperProxy.java:159)
	at com.mybatisflex.core.mybatis.binding.FlexMapperProxy.invoke(FlexMapperProxy.java:85)
	at jdk.proxy3/jdk.proxy3.$Proxy122.selectAllWithRelations(Unknown Source)
	at ymirlabs.base.mapper_demo.RelationOneToManyTest.queryWithValueField(RelationOneToManyTest.java:36)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

看mybatis-flex源码，是在这一行去找的 `UserMapper` 和 `User：

 https://github.com/mybatis-flex/mybatis-flex/blob/1028bbd58c3b621f4668b4fe3c274ba073a163b1/mybatis-flex-core/src/main/java/com/mybatisflex/core/relation/AbstractRelation.java#L95
