### ISSUE TITLE
Db.updateById运行报错

### ISSUE THREAD

**Issue by VF202307** [mybatis-flex/mybatis-flex#395]
在测试代码里写了如下几行代码

```
Row row = Db.selectOneById("user", "id", 1)
row.set("username", "test")
Db.updateById('user', row)
```

运行后报错，不知道那里有问题。

错误信息如下：
Caught: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method 'public static java.lang.String com.mybatisflex.core.provider.RowSqlProvider.updateById(java.util.Map)' with specify parameter 'class org.apache.ibatis.binding.MapperMethod$ParamMap'.  Cause: java.lang.NullPointerException
org.apache.ibatis.exceptions.PersistenceException: 
### Cause: org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method 'public static java.lang.String com.mybatisflex.core.provider.RowSqlProvider.updateById(java.util.Map)' with specify parameter 'class org.apache.ibatis.binding.MapperMethod$ParamMap'.  Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:67)
	at com.mybatisflex.core.mybatis.binding.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:146)
	at com.mybatisflex.core.mybatis.binding.FlexMapperProxy.invoke(FlexMapperProxy.java:85)

**Comment by VF202307** [comment]
已解决, 必须指定Key才能正常执行.
```
Row row = Row.ofKey("id", 42)
row.set("username", "test")
Db.updateById("user", row)
```
