### ISSUE TITLE
在使用mybatis-flex过程中，使用原生xml写法进行复杂嵌套查询报错，以前的项目只使用mybatis进行查询时没有任何问题

### ISSUE THREAD

**Issue by mujinming** [mybatis-flex/mybatis-flex#402]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.apache.ibatis.type.TypeHandlerRegistry.getJdbcHandlerMap(TypeHandlerRegistry.java:259)
	at org.apache.ibatis.type.TypeHandlerRegistry.getTypeHandler(TypeHandlerRegistry.java:242)
	at org.apache.ibatis.type.TypeHandlerRegistry.getTypeHandler(TypeHandlerRegistry.java:218)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.prepareSimpleKeyParameter(FlexDefaultResultSetHandler.java:963)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.prepareParameterForNestedQuery(FlexDefaultResultSetHandler.java:951)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.getNestedQueryMappingValue(FlexDefaultResultSetHandler.java:921)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.getPropertyMappingValue(FlexDefaultResultSetHandler.java:521)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.applyPropertyMappings(FlexDefaultResultSetHandler.java:494)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.getRowValue(FlexDefaultResultSetHandler.java:417)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.handleRowValuesForSimpleResultMap(FlexDefaultResultSetHandler.java:365)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.handleRowValues(FlexDefaultResultSetHandler.java:335)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.handleResultSet(FlexDefaultResultSetHandler.java:306)
	at com.mybatisflex.core.mybatis.FlexDefaultResultSetHandler.handleResultSets(FlexDefaultResultSetHandler.java:191)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:66)
	at com.mybatisflex.core.mybatis.FlexStatementHandler.query(FlexStatementHandler.java:101)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:65)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:336)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:158)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:110)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:90)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154)

**Comment by Suomm** [comment]
fixed.
