### ISSUE TITLE
 Solon 3.0.1使用mybatis-flex-solon-plugin 1.9.7报错

### ISSUE THREAD

**Issue by xiangtuocloud** [mybatis-flex/mybatis-flex#412]
```
   <parent>
        <groupId>org.noear</groupId>
        <artifactId>solon-parent</artifactId>
        <version>3.0.1</version>
        <relativePath />
    </parent>

        <dependency>
            <groupId>com.mybatis-flex</groupId>
            <artifactId>mybatis-flex-solon-plugin</artifactId>
            <version>1.9.7</version>
        </dependency>
```
```
ERROR 2024-10-11 17:15:47.419 #21384 [-main][*][@pid:21384][org.noear.solon.Solon]:
Solon start failed: Event execution failed: org.noear.solon.core.event.AppPluginLoadEndEvent
org.noear.solon.core.exception.EventException: Event execution failed: org.noear.solon.core.event.AppPluginLoadEndEvent
at org.noear.solon.core.event.EventBus.publish(EventBus.java:88) ~[solon-3.0.1.jar:?]
at org.noear.solon.SolonApp.run(SolonApp.java:242) ~[solon-3.0.1.jar:?]
at org.noear.solon.SolonApp.start(SolonApp.java:147) ~[solon-3.0.1.jar:?]
at org.noear.solon.Solon.start(Solon.java:185) [solon-3.0.1.jar:?]
at org.noear.solon.Solon.start(Solon.java:145) [solon-3.0.1.jar:?]
at cn.ahsdxy.hi.MainApp.main(MainApp.java:11) [classes/:?]
Caused by: java.lang.NoSuchMethodError: 'void org.noear.solon.core.event.EventBus.push(java.lang.Object)'
at com.mybatisflex.solon.integration.MybatisAdapterFlex.initConfiguration(MybatisAdapterFlex.java:97) ~[mybatis-flex-solon-plugin-1.9.7.jar:?]
```

**Comment by yangfuhai** [comment]
1.9.8 已经 push Maven 仓库。
