### ISSUE TITLE
代码生成工具创建 Entity 失败：Shared method not found: isNotBlank

### ISSUE THREAD

**Issue by uRickLee** [mybatis-flex/mybatis-flex#427]
mybatis-flex 版本：1.9.9 

mybatis-flex-codegen 创建工具模板没有 isNotBlank 静态共享方法，生成 Entity 失败。通过自定义 **EnjoyTemplate** 能够解决。

```

com.jfinal.template.TemplateException: Shared method not found: isNotBlank(java.lang.String)
Template: "/templates/enjoy/entityOrBase.tpl". Line: 80
	at com.jfinal.template.expr.ast.SharedMethod.eval(SharedMethod.java:63)
	at com.jfinal.template.stat.ast.If.exec(If.java:53)
	at com.jfinal.template.stat.ast.StatList.exec(StatList.java:68)
	at com.jfinal.template.stat.ast.For.forIterator(For.java:74)
	at com.jfinal.template.stat.ast.For.exec(For.java:53)
	at com.jfinal.template.stat.ast.StatList.exec(StatList.java:68)
	at com.jfinal.template.Template.render(Template.java:57)
	at com.mybatisflex.codegen.template.impl.EnjoyTemplate.generate(EnjoyTemplate.java:66)
	at com.mybatisflex.codegen.generator.impl.EntityGenerator.genEntityClass(EntityGenerator.java:118)
	at com.mybatisflex.codegen.generator.impl.EntityGenerator.generate(EntityGenerator.java:60)
	at com.mybatisflex.codegen.Generator.generate(Generator.java:72)
	at com.mybatisflex.codegen.Generator.generate(Generator.java:58)
	at site.iou.samlliou.mybatisflex.GeneratorTest.createModel(GeneratorTest.java:32)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	```

**Comment by yangfuhai** [comment]
新版本修复了
