### ISSUE TITLE
抽取数据库实体类对象的公共属性，子类继承公共类，使用save()方法报错，测试单元中却不报错

### ISSUE THREAD

**Issue by Astrsea** [mybatis-flex/mybatis-flex#441]
## 基类
```java
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer;
import com.mybatisflex.annotation.Column;
import com.mybatisflex.annotation.Id;
import com.mybatisflex.annotation.KeyType;
import com.mybatisflex.core.activerecord.Model;
import com.mybatisflex.core.keygen.KeyGenerators;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.MappedSuperclass;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serial;
import java.time.LocalDateTime;

@MappedSuperclass
@EqualsAndHashCode(callSuper = true)
@Data
public class BaseEntity<T extends BaseEntity<T>> extends Model<T> {

    @Serial
    private static final long serialVersionUID = 1L;

    @Schema(name = "主键ID")
    @jakarta.persistence.Id
    @Id(keyType = KeyType.Generator, value = KeyGenerators.snowFlakeId)
    @jakarta.persistence.Column(name = "id", unique = true, nullable = false, columnDefinition = "VARCHAR(64) COMMENT '主键ID'")
    private String id;

    @Schema(name = "租户ID")
    @Column(tenantId = true)
    @jakarta.persistence.Column(name = "tenant_id", columnDefinition = "VARCHAR(8) COMMENT '租户ID'")
    private Long tenantId;

    @Schema(name = "版本号")
    @Column(version = true)
    @jakarta.persistence.Column(name = "version", columnDefinition = "SMALLINT DEFAULT 0 COMMENT '版本号'")
    private Long version;

    @Schema(name = "创建者账号")
    @jakarta.persistence.Column(name = "created_by", columnDefinition = "VARCHAR(64) COMMENT '创建者账号'")
    private String createdBy;

    @Schema(name = "修改者账号")
    @jakarta.persistence.Column(name = "updated_by", columnDefinition = "VARCHAR(64) COMMENT '修改者账号'")
    private String updatedBy;

    @Schema(name = "创建时间")
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @jakarta.persistence.Column(name = "created_at", columnDefinition = "DATETIME COMMENT '创建时间'")
    private LocalDateTime createdAt;

    @Schema(name = "修改时间")
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @jakarta.persistence.Column(name = "updated_at", columnDefinition = "DATETIME COMMENT '更新时间'")
    private LocalDateTime updatedAt;
}
```

## 继承类
```java
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

@EqualsAndHashCode(callSuper = true)
@Data(staticConstructor = "create")
@Accessors(chain = true)
@Entity
@Table(name = "system_ip_blacklist")
@com.mybatisflex.annotation.Table("system_ip_blacklist")
public class SystemIpBlacklist extends BaseEntity<SystemIpBlacklist> {

    @Schema(name = "被请求的类")
    @Column(name = "function_class", columnDefinition = "VARCHAR(255) COMMENT '被请求的类'")
    private String functionClass;

    @Schema(name = "被请求的方法")
    @Column(name = "function_name", columnDefinition = "VARCHAR(255) COMMENT '被请求的方法'")
    private String functionName;

    @Schema(name = "客户端IP地址")
    @Column(name = "remote_address", columnDefinition = "VARCHAR(64) COMMENT '客户端IP地址'")
    private String remoteAddress;

    @Schema(name = "备注说明")
    @Column(name = "remake", columnDefinition = "VARCHAR(255) COMMENT '备注说明'")
    private String remake;
}
```

## 使用
```java
  SystemIpBlacklist
  .create()
  .setFunctionClass("functionClass")
  .setFunctionName("functionName")
  .setRemoteAddress("ip")
  .setRemake("reason")
  .save();
```

## 测试单元中运行结果（正常）
![image](https://github.com/user-attachments/assets/431b1416-0650-492a-a124-84ec9e3bcb4f)

## 服务中运行结果（异常）
```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: com.mybatisflex.core.exception.MybatisFlexException: java.lang.RuntimeException: java.lang.IllegalArgumentException: object of type cloud.astrsea.framework.model.entity.mysql.SystemIpBlacklist is not an instance of cloud.astrsea.framework.model.entity.mysql.BaseEntity
### Cause: com.mybatisflex.core.exception.MybatisFlexException: java.lang.RuntimeException: java.lang.IllegalArgumentException: object of type cloud.astrsea.framework.model.entity.mysql.SystemIpBlacklist is not an instance of cloud.astrsea.framework.model.entity.mysql.BaseEntity
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at com.mybatisflex.core.mybatis.binding.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:146)
	at com.mybatisflex.core.mybatis.binding.FlexMapperProxy.invoke(FlexMapperProxy.java:85)
	at jdk.proxy3/jdk.proxy3.$Proxy205.insert(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.mybatisflex.core.mybatis.Mappers$MapperHandler.invoke(Mappers.java:111)
	at jdk.proxy3/jdk.proxy3.$Proxy205.insert(Unknown Source)
	at com.mybatisflex.core.activerecord.MapperModel.save(MapperModel.java:92)
	at com.mybatisflex.core.activerecord.MapperModel.save(MapperModel.java:71)
	at cloud.astrsea.framework.annotation.limiter.RateLimiterAspect.before(RateLimiterAspect.java:89)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```
![image](https://github.com/user-attachments/assets/7eee5cf6-0c22-47d9-ace3-b81656d7fd71)
![image](https://github.com/user-attachments/assets/f8da989e-ca90-4154-b8c6-d99cfcb86b96)

**Comment by Astrsea** [comment]
经过测试发现是Id注解有问题，当使用 Id 注解 指定keyType为KeyType.Generator, value为任意值（KeyGenerators中的任意生成器或者自定义生成器） 时都会出现该问题

**Comment by Astrsea** [comment]
> 经过测试发现是Id注解有问题，当使用 Id 注解 指定keyType为KeyType.Generator, value为任意值（KeyGenerators中的任意生成器或者自定义生成器） 时都会出现该问题 @yangfuhai

https://mybatis-flex.com/zh/faq.html#springboot-%E9%A1%B9%E7%9B%AE%E4%B8%AD%E5%87%BA%E7%8E%B0-class-comxxx-cannot-be-cast-class-comxxx-%E7%9A%84%E9%94%99%E8%AF%AF
