### ISSUE TITLE
1.10.2版本exists条件SQL用错了表名, 别名存在时，应当用别名

### ISSUE THREAD

**Issue by xiejx618** [mybatis-flex/mybatis-flex#442]
1.查询代表如下：
```
QueryWrapper queryWrapper = QueryWrapper.create()
                .select(USER.ID.as(UserVO::getUserId), USER.NAME.as(UserVO::getUserName))
                .from(USER.as("u"))
                .where(USER.NAME.like("xie")
                        .and(exists(selectOne().from(USER_ROLE).where(USER_ROLE.USER_ID.eq(USER.ID).and(USER_ROLE.ROLE_ID.ge(1)))))
                );
        List<UserVO> userVOS = userMapper.selectListByQueryAs(queryWrapper, UserVO.class);
```
2.执行报错:
```
processing failed: org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'us_user.id' in 'where clause'
### The error may exist in org/exam/demo/mapper/UserMapper.java (best guess)
### The error may involve org.exam.demo.mapper.UserMapper.selectListByQuery
### The error occurred while executing a query
### SQL: SELECT `id` AS `user_id`, `name` AS `user_name` FROM `us_user` AS `u` WHERE `name` LIKE ? AND EXISTS (SELECT 1 AS `temp_one` FROM `us_user_role` WHERE `user_id` = `us_user`.`id` AND `role_id` >= ?)
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'us_user.id' in 'where clause'
; bad SQL grammar []] with root cause

java.sql.SQLSyntaxErrorException: Unknown column 'us_user.id' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:988) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:382) ~[mysql-connector-j-9.1.0.jar:9.1.0]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-5.1.0.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-5.1.0.jar:na]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65) ~[mybatis-3.5.16.jar:3.5.16]
	at com.mybatisflex.core.mybatis.FlexStatementHandler.lambda$query$2(FlexStatementHandler.java:100) ~[mybatis-flex-core-1.10.1.jar:na]
	at com.mybatisflex.core.audit.AuditManager.startAudit(AuditManager.java:114) ~[mybatis-flex-core-1.10.1.jar:na]
	at com.mybatisflex.core.mybatis.FlexStatementHandler.query(FlexStatementHandler.java:100) ~[mybatis-flex-core-1.10.1.jar:na]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:65) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:336) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:158) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:110) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:90) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:142) ~[mybatis-3.5.16.jar:3.5.16]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:333) ~[mybatis-spring-3.0.4.jar:3.0.4]
	at jdk.proxy2/jdk.proxy2.$Proxy64.selectList(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:194) ~[mybatis-spring-3.0.4.jar:3.0.4]
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147) ~[mybatis-3.5.16.jar:3.5.16]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80) ~[mybatis-3.5.16.jar:3.5.16]
	at com.mybatisflex.core.mybatis.binding.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:146) ~[mybatis-flex-core-1.10.1.jar:na]
	at com.mybatisflex.core.mybatis.binding.FlexMapperProxy.invoke(FlexMapperProxy.java:85) ~[mybatis-flex-core-1.10.1.jar:na]
	at jdk.proxy2/jdk.proxy2.$Proxy66.selectListByQuery(Unknown Source) ~[na:na]
	at com.mybatisflex.core.BaseMapper.selectListByQueryAs(BaseMapper.java:759) ~[mybatis-flex-core-1.10.1.jar:na]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[na:na]
	at com.mybatisflex.core.mybatis.binding.MybatisMapperProxy$DefaultMethodInvoker.invoke(MybatisMapperProxy.java:159) ~[mybatis-flex-core-1.10.1.jar:na]
	at com.mybatisflex.core.mybatis.binding.FlexMapperProxy.invoke(FlexMapperProxy.java:85) ~[mybatis-flex-core-1.10.1.jar:na]
	at jdk.proxy2/jdk.proxy2.$Proxy66.selectListByQueryAs(Unknown Source) ~[na:na]
	at org.exam.demo.web.UserController.test(UserController.java:67) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188) ~[spring-web-6.2.0.jar:6.2.0]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.2.0.jar:6.2.0]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:986) ~[spring-webmvc-6.2.0.jar:6.2.0]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:891) ~[spring-webmvc-6.2.0.jar:6.2.0]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.2.0.jar:6.2.0]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1088) ~[spring-webmvc-6.2.0.jar:6.2.0]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:978) ~[spring-webmvc-6.2.0.jar:6.2.0]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.2.0.jar:6.2.0]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.2.0.jar:6.2.0]
```

**Comment by xiejx618** [comment]
虽然可以将USER.ID可以改为 USER.as(""u).ID ，看似解决了当前问题。  但这种能自动判断的就不要还要显式指定了。
看了下com.mybatisflex.core.query.QueryColumn#getSelectTable的逻辑，感觉还是不太合理。我个人理解：
1.  join的on字段获取表别名，应考虑from表和前面已经写的join表。
2.  where的普通字段获取表别名，应考虑from表和join表。
3.  exist这样的子查询，要考虑当前子查询的from表和join表，如果子查询找不到，还要找父查询。


当前考虑做数据权限组件，  不可能一个字段出现问题，就显式指定一下，这样是做不了组件
