### ISSUE TITLE
code generator error

### ISSUE THREAD

**Issue by liuyuliang092** [mybatis-flex/mybatis-flex#48]
### version
```
mybatis-flex version：1.3.0
mybatis-flex-codegen version:1.3.5
springboot verison：2.7.12
```

### The POM is as follows
```
<dependency>
            <groupId>com.mybatis-flex</groupId>
            <artifactId>mybatis-flex-spring-boot-starter</artifactId>
            <version>1.3.0</version>
        </dependency>

        <dependency>
            <groupId>com.mybatis-flex</groupId>
            <artifactId>mybatis-flex-processor</artifactId>
            <version>1.3.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>4.0.3</version>
        </dependency>

        <dependency>
            <groupId>com.mybatis-flex</groupId>
            <artifactId>mybatis-flex-codegen</artifactId>
            <version>1.3.5</version>
        </dependency>

        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
            <version>8.0.32</version>
        </dependency>
```

### issue：
```
An error is reported when the code generator generates the implementation class, and the default template of the implementation class is null。
```

### The code generator code is as follows
```
public class Codegen {
    public static void main(String[] args) {
        //配置数据源
        HikariDataSource dataSource = new HikariDataSource();
        dataSource.setJdbcUrl("jdbc:mysql://127.0.0.1:3306/fed_portal?characterEncoding=utf-8");
        dataSource.setUsername("portal");
        dataSource.setPassword("fed_portal");
        //创建配置内容，两种风格都可以。
        GlobalConfig globalConfig = createGlobalConfigUseStyle2();
        //通过 datasource 和 globalConfig 创建代码生成器
        Generator generator = new Generator(dataSource, globalConfig);
        //生成代码
        generator.generate();
    }
    public static GlobalConfig createGlobalConfigUseStyle2() {
        //创建配置内容
        GlobalConfig globalConfig = new GlobalConfig();
        //设置根包
        globalConfig.getPackageConfig()
                .setSourceDir("E://2023/mybatis-flex")
                .setBasePackage("com.tech.fate.portal.web");
        //设置表前缀和只生成哪些表
        globalConfig.getStrategyConfig()
                .setGenerateTable("project_participant");
        //设置生成 entity 并启用 Lombok
        globalConfig.enableEntity()
                .setWithLombok(true);
        //设置生成 mapper
        globalConfig.enableMapper();
        globalConfig.enableController();
        globalConfig.enableService();
        globalConfig.enableServiceImpl();
        return globalConfig;
    }
}

```

### The console error log is as follows：
```
com.jfinal.template.TemplateException: null
Template: "/templates/enjoy/serviceImpl.tpl". Line: 1
	at com.jfinal.template.expr.ast.Field.eval(Field.java:86)
	at com.jfinal.template.expr.ast.Assign.assignVariable(Assign.java:102)
	at com.jfinal.template.expr.ast.Assign.eval(Assign.java:95)
	at com.jfinal.template.stat.ast.Set.exec(Set.java:57)
	at com.jfinal.template.stat.ast.StatList.exec(StatList.java:68)
	at com.jfinal.template.Template.render(Template.java:57)
	at com.mybatisflex.codegen.template.impl.EnjoyTemplate.generate(EnjoyTemplate.java:51)
	at com.mybatisflex.codegen.generator.impl.ServiceImplGenerator.generate(ServiceImplGenerator.java:73)
	at com.mybatisflex.codegen.Generator.generate(Generator.java:67)
	at com.tech.fate.portal.web.commons.Codegen.main(Codegen.java:41)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jfinal.template.expr.ast.FieldGetters$IsMethodFieldGetter.get(FieldGetters.java:130)
	at com.jfinal.template.expr.ast.Field.eval(Field.java:81)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: com/mybatisflex/spring/service/impl/CacheableServiceImpl
	at com.mybatisflex.codegen.config.ServiceImplConfig.isCacheExample(ServiceImplConfig.java:127)
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.mybatisflex.spring.service.impl.CacheableServiceImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 16 more
```

**Comment by Suomm** [comment]
mybatis-flex version：1.3.0
mybatis-flex-codegen version:1.3.5

这两个版本没有对上（these two versions do not correspond）：1.3.0 - 1.3.5
