### ISSUE TITLE
无法使用UpdateEntity

### ISSUE THREAD

**Issue by jackson-som** [mybatis-flex/mybatis-flex#68]
想要执行的代码：
``` java
AccountDAO updateAccount = UpdateEntity.of(AccountDAO.class, info.getId());
updateAccount.setAge(info.getAge());

mapper.update(updateAccount); // 执行 <Mapper> 里的 <update()>
// updateById(updateAccount); // 执行 <ServiceImpl> 里的 <updateById()>
```

以下是报错的信息：
```
Caused by: org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method 'public static java.lang.String com.mybatisflex.core.provider.EntitySqlProvider.update(java.util.Map,org.apache.ibatis.builder.annotation.ProviderContext)' with specify parameter 'class org.apache.ibatis.binding.MapperMethod$ParamMap'.  Cause: java.lang.NullPointerException: Cannot invoke "com.mybatisflex.core.table.ColumnInfo.buildTypeHandler()" because "columnInfo" is null
  at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:209)
  at org.apache.ibatis.builder.annotation.ProviderSqlSource.getBoundSql(ProviderSqlSource.java:165)
  at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:320)
  at org.apache.ibatis.executor.statement.BaseStatementHandler.<init>(BaseStatementHandler.java:65)
  at org.apache.ibatis.executor.statement.PreparedStatementHandler.<init>(PreparedStatementHandler.java:42)
  at com.mybatisflex.core.mybatis.FlexPreparedStatementHandler.<init>(FlexPreparedStatementHandler.java:38)
  at com.mybatisflex.core.mybatis.FlexStatementHandler.<init>(FlexStatementHandler.java:58)
  at com.mybatisflex.core.mybatis.FlexConfiguration.newStatementHandler(FlexConfiguration.java:117)
  at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)
  at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
  at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
  at jdk.proxy2/jdk.proxy2.$Proxy237.update(Unknown Source)
  at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
  ... 154 more
Caused by: java.lang.reflect.InvocationTargetException
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.apache.ibatis.builder.annotation.ProviderSqlSource.invokeProviderMethod(ProviderSqlSource.java:248)
  at org.apache.ibatis.builder.annotation.ProviderSqlSource.createSqlSource(ProviderSqlSource.java:177)
  ... 176 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.mybatisflex.core.table.ColumnInfo.buildTypeHandler()" because "columnInfo" is null
  at com.mybatisflex.core.table.TableInfo.buildUpdateSqlArgs(TableInfo.java:619)
  at com.mybatisflex.core.provider.EntitySqlProvider.update(EntitySqlProvider.java:239)
  ... 182 more

```

以上的方法都行不通。

以下是目前解决方法：

``` java
AccountDAO updateAccount = new AccountDAO(); // 不使用 UpdateEntity
updateAccount.setId(info.getId());
updateAccount.setAge(info.getAge());

// 两种方法都行
mapper.update(updateAccount); // 执行 <Mapper> 里的 <update()>
// updateById(updateAccount); // 执行 <ServiceImpl> 里的 <updateById()>
```

另外，不明白使用 UpdateEntity 的意义是什么，还是说需要配合 UpdateWrapper 一起使用？能够请教说明下吗？

**Comment by Suomm** [comment]
可以看一下课程：

【MyBatis-Flex 视频教程 - 10更新数据】 https://www.bilibili.com/video/BV1Cg4y1w79y/?share_source=copy_web&vd_source=6986f9a4ec12e628ff34aa4316d740fe

【MyBatis-Flex 视频教程 - 11复杂更新】 https://www.bilibili.com/video/BV1wu411L7dF/?share_source=copy_web&vd_source=6986f9a4ec12e628ff34aa4316d740fe

**Comment by yangfuhai** [comment]
新版本未发现问题。
